---
# Run with:
#   ansible-playbook -i inventories/aem.ini playbooks/aem_master.yml
# Tags: stop, patch, reboot, start, publisher, dispatcher

- name: Stop AEM servers
  hosts: aut:pub:dis
  gather_facts: false
  serial: 1
  max_fail_percentage: 100
  roles:
    - { role: stop_aem, tags: ["stop"] }

- name: Patch and reboot servers
  hosts: aut:pub:dis
  gather_facts: true
  serial: 1
  max_fail_percentage: 100
  roles:
    - { role: patch_reboot, tags: ["patch","reboot"] }

- name: Start AEM servers
  hosts: aut:pub:dis
  gather_facts: true
  serial: 1
  max_fail_percentage: 100
  roles:
    - { role: start_aem, tags: ["start"] }

- name: Validate AEM Publisher
  hosts: pub
  gather_facts: false
  serial: 1
  max_fail_percentage: 100
  roles:
    - { role: validate_publisher, tags: ["publisher"] }

- name: Validate AEM Dispatcher
  hosts: dis
  gather_facts: false
  serial: 1
  max_fail_percentage: 100
  roles:
    - { role: validate_dispatcher, tags: ["dispatcher"] }
